package name.abuchen.portfolio.rebalance;

import name.abuchen.portfolio.snapshot.PerformanceIndex;

/**
 * Represents a proposed transaction generated by the RebalancingEngine.
 * Contains the necessary information to execute a rebalancing move.
 */
public class Order
{
    
    public enum OrderSide
    {
        BUY,
        SELL
    }

    private final PerformanceIndex asset;
    private final OrderSide side;
    private final double quantity;
    private final double estimatedPrice;

    public Order(PerformanceIndex asset, OrderSide side, double quantity, double estimatedPrice)
    {
        this.asset = asset;
        this.side = side;
        this.quantity = quantity;
        this.estimatedPrice = estimatedPrice;
    }

    public PerformanceIndex getAsset()
    {
        return asset;
    }

    public OrderSide getSide()
    {
        return side;
    }

    public double getQuantity()
    {
        return quantity;
    }

    public double getEstimatedPrice()
    {
        return estimatedPrice;
    }
    
    /**
     * @return the total estimated value of this order (quantity * price).
     */
    public double getTotalValue()
    {
        return quantity * estimatedPrice;
    }

    /**
     * Returns a new Order with the same fields but a different quantity.
     */
    public Order withQuantity(double newQuantity)
    {
        return new Order(this.asset, this.side, newQuantity, this.estimatedPrice);
    }
}
